name: Spring Boot Maven CI

on:
  push:
    branches:
      - master   # Change this to your main branch name

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest   # You can choose the OS for your build environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change this to your desired Java version

      - name: Build with Maven
        run: mvn package   # You can customize the build command based on your project

      - name: Run Tests
        run: mvn test      # Customize the test command as per your project structure
